### ISSUE TITLE
Question: Facing issue in running txwifi when cloned from git repo

### ISSUE THREAD

**Issue by Sharvin26** [txn2/txwifi#10]
* **I'm submitting a ...**
  - [x] Question

* **What is the current behavior?**
When running the tx wifi container I get following error =>

```
{"hostname":"51910a099cf4","level":30,"msg":"Starting IoT Wifi...","name":"txwifi","pid":0,"time":"2019-07-25T07:37:46.214Z","v":0}
panic: open cfg/wificfg.json: no such file or directory

goroutine 1 [running]:
github.com/txn2/txwifi/iotwifi.loadCfg(0x2a5481, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/txn2/txwifi/iotwifi/iotwifi.go:76 +0x264
github.com/txn2/txwifi/iotwifi.NewWpaCfg(0x2a27ef, 0x6, 0x2a2442, 0x5, 0x2dd3a0, 0x10a0c0f8, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/txn2/txwifi/iotwifi/wpacfg.go:46 +0x24
main.main()
	/go/src/github.com/txn2/txwifi/main.go:55 +0x2d4
```

* **Steps to Reproduce the problem** 

1. git clone -b develop https://github.com/txn2/txwifi.git
2. cd txwifi
3. wget https://raw.githubusercontent.com/txn2/txwifi/master/cfg/wificfg.json
4. nano wificfg.json # Edited the wificfg.json
5. mv wificfg.json cfg/
6. docker build -t wifi-connect .
7. docker run wifi-connect --rm --privileged --net host -v $(pwd)/cfg/wificfg.json:/go/src/github.com/txn2/txwifi/cfg/wificfg.json

* **What is the expected behavior?**

When I pulled the txwifi image from the docker hub then it was working properly. But when I ran this manually using the above steps I am getting the error `panic: open cfg/wificfg.json: no such file or directory`.

* **Please tell us about your environment:**
  
  - Device: Raspberry pi 3 b+
  - OS: Raspbian Stretch

**Comment by sergge1** [comment]
@Sharvin26  what was your solution for this issue?
