### ISSUE TITLE
Network still available after container removal

### ISSUE THREAD

**Issue by sergge1** [txn2/txwifi#13]
* **I'm submitting a ...**
  - [X] bug report

* **What is the current behavior?**
When container is stopped by the command `docker stop <NAME>` the AP network (configured within  wificfg.json) remains available untill Raspberry reboot.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1. Docker installation
2. txn2/txwifi downloading by `docker pull cjimti/iotwifi` command
3. txn2/txwifi container run by respective command -> uap0 interface for AP is created with iot-wifi-cfg-3 network available for connection.
4. txn2/txwifi container stop/remove by respective commands

* **What is the expected behavior?**
After the container stop/removal, the network interface should be stopped.

* **What is the motivation / use case for changing the behavior?**
Its a logical behavior

* **Please tell us about your environment:**
  
  - Device: Rasp 3B+
  - OS: Stretch

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cjimti** [comment]
The container is intended to set up the wifi network access. If the container is stopped or removed it has no ability to perform any operations.
