### ISSUE TITLE
NOISSUE: embedding txwifi

### ISSUE THREAD

**Issue by beres** [txn2/txwifi#6]
Since i don't need/want docker and want to embed it into another app, i've made some changes.
I don't request a pull because i don't know if you agree, you can take a look here 
https://github.com/beres/txwifi/commit/b68393b12937e18edde43dc45f70cdbc03ef9e6d or check out the master branch to take a look.

* what have modified
Added these two config options
  - DontFallBackToApMode
  - AllowStartStop, permit to enable two method that start or stop the wifi. One the user access the device via ap, it could decide to disable wifi and configure cabled network. The configuration is not part of this project, simply add a third case AP/CL/OFF
 - if WpaPassphrase is empty in configuration file, the ap start without auth support

* other changes
  - replaced go-bunyan/bunyan with sirupsen/logrus
  - added two example server_gin and server_gorilla

If you are interested we could discuss how and what to merge

Best Regards
ale

**Comment by cjimti** [comment]
@beres sounds interesting, @LelandSindt has begun maintaining this project. I believe he is traveling for a bit but will likely check issues when he is back.

Thanks for the input!

**Comment by LelandSindt** [comment]
@beres thank you! 

I will be reviewing your modifications and most likely lifting the DontFallBack... logic.
