### ISSUE TITLE
Adding support for networking across Pi Zero usb0 interface

### ISSUE THREAD

**Issue by deftdawg** [txn2/txwifi#7]
Discovered this project this weekend and am currently running an ``cjimti/iotwifi`` image on hypriot v1.11.0b3 on a Raspberry Pi Zero W (Tried to pull ``txn2/txwifi`` however it gives ``not found: manifest unknown``).   

The Pi Zero W can configure it's usb port to act as an USB-OTG RNDIS ethernet device (usb0), which my Zero W can use to communicate to the internet.

I'm wondering if modifying this image to route uap0 -> usb0 when wlan0 is not connected to a client would be possible (or just uap0 -> usb0 all the time would be ok too)...  

Anyway, if there are any config files you can point me to that'd be helpful otherwise I'll just grep around in /etc tomorrow. 

Must say your docker image is pretty sweet. :)

**Comment by LelandSindt** [comment]
@deftdawg 

You are going to want to work from the development branch and  have a look at the RunWifii function.

Link: https://github.com/txn2/txwifi/blob/cee0cca17f5b10b10d4630b48825254024211e94/iotwifi/iotwifi.go#L174

Note, there are considerable changes that have not been pushed to master, and you will need to build the image locally.
