### ISSUE TITLE
Connecting to multiple Wifi networks

### ISSUE THREAD

**Issue by VinS101** [txn2/txwifi#8]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
I believe it is a feature

* **What is the current behavior?**
Currently, we are able to connect to only one Wifi access point. I would like to be able to connect to multiple Wifi networks from my Raspberry Pi.

* **What is the motivation / use case for changing the behavior?**
Connecting two or more networks is highly desirable in certain situations.

* **Please tell us about your environment:**
  
  - Device: Raspberry Pi 3 B+
  - OS: Raspbian NOOBS

**Comment by cjimti** [comment]
I am not sure how the pi would connect to more than one network, are you looking to multiplexing?

**Comment by VinS101** [comment]
I was able to achieve this using https://github.com/tomeshnet/prototype-cjdns-pi
